id = "cairo"
name = "Cairo"
version = "0.0.8"
schema_version = 1
authors = ["Franco 0xpantera@proton.me"]
description = "Cairo language support for Zed"
repository = "https://github.com/0xpantera/zed-cairo"

[grammars.cairo]
repository = "https://github.com/starkware-libs/tree-sitter-cairo"
rev = "4c6a25680546761b80a710ead1dd34e76c203125"

[language_servers.cairo]
name = "Cairo Language Server"
languages = ["Cairo"]
supports_workspace_configuration = true
