id = "zed-cairo"
name = "Cairo"
version = "0.0.1"
schema_version = 1
authors = ["Thomas Robert Butler IV trbiv@proton.me"]
description = "Cairo language support for the Zed editor"
repository = "https://github.com/trbutler4/zed-cairo"

#[grammars.cairo]
#repository = "https://github.com/trbutler4/tree-sitter-cairo"
#commit = "ee87b0e415eff54a17e5bef5945b989ca11a0e0e"

[language_servers.cairo]
name = "Cairo LSP"
language = "Cairo"
