id = "zed-cairo"
name = "Cairo"
version = "0.0.1"
schema_version = 1
authors = ["Thomas Robert Butler IV trbiv@proton.me"]
description = "Cairo language support for the Zed editor"
repository = "https://github.com/trbutler4/zed-cairo"

[grammars.cairo]
repository = "https://github.com/trbutler4/tree-sitter-cairo-zed"
commit = "691a597b761fcd977e6904a9f18b29729ca9d1f3"

[language_servers.cairo]
name = "Cairo LSP"
language = "Cairo"
