id = "zed-cairo"
name = "Cairo"
version = "0.0.1"
schema_version = 1
authors = ["Thomas Robert Butler IV trbiv@proton.me"]
description = "Cairo language support for the Zed editor"
repository = "https://github.com/trbutler4/zed-cairo"

[grammars.cairo]
repository = "https://github.com/trbutler4/tree-sitter-cairo"
commit = "98db316d20acc822c0346c9e8e0e9b894a679b5e"

[language_servers.cairo]
name = "Cairo LSP"
language = "Cairo"
